### ISSUE TITLE
How to use my own data to create a map？

### ISSUE THREAD

**Issue by 78748547** [YixFeng/Block-Map-Based-Localization#1]
Thanks for your great work, I would like to ask how to build a map using my own equipment or BAG package. I'm looking at two _.yaml_ files, can I use them by just providing the lidar and IMU topics? Thanks.

**Comment by YixFeng** [comment]
> Thanks for your great work, I would like to ask how to build a map using my own equipment or BAG package. I'm looking at two _.yaml_ files, can I use them by just providing the lidar and IMU topics? Thanks.

If you have ground-truth or high-precision poses, you can use [https://github.com/YixFeng/Block_Map_from_Groundtruth](https://github.com/YixFeng/Block_Map_from_Groundtruth) to build your own Block-Maps. The parameter `blockSize` in *cfg.yaml* means the size of each BM. 
After constructing BMs, you can create a new *.yaml* file and provide your parameters in it, such as topics of the LiDAR and IMU, the extrinsics between these two, the transformation between the LiDAR frame and the frame of the poses you use in BM generating (If you use the same frame, leave it as an identity matrix), and the directory of your BMs. 

If you have any other questions, feel free to ask me.

**Comment by 78748547** [comment]
> > Thanks for your great work, I would like to ask how to build a map using my own equipment or BAG package. I'm looking at two _.yaml_ files, can I use them by just providing the lidar and IMU topics? Thanks.
> 
> If you have ground-truth or high-precision poses, you can use https://github.com/YixFeng/Block_Map_from_Groundtruth to build your own Block-Maps. The parameter `blockSize` in _cfg.yaml_ means the size of each BM. After constructing BMs, you can create a new _.yaml_ file and provide your parameters in it, such as topics of the LiDAR and IMU, the extrinsics between these two, the transformation between the LiDAR frame and the frame of the poses you use in BM generating (If you use the same frame, leave it as an identity matrix), and the directory of your BMs.
> 
> If you have any other questions, feel free to ask me.

Thanks for your answer！
