### ISSUE TITLE
A issue about global_localization.

### ISSUE THREAD

**Issue by zuowei1998** [YixFeng/Block-Map-Based-Localization#2]
Thank you for your outstanding work! I was wondering when you plan to open-source the global localization part of your code. I have a few questions about the global localization algorithm presented in your paper. Specifically, I'd like to know what improvements your algorithm has over the BBS algorithm. In addition to the initial score S0 and greedy strategy (I'm assuming this means searching in order of score from highest to lowest), are there any other algorithmic optimizations that you could share more details about?

**Comment by YixFeng** [comment]
@Ericsii

**Comment by Ericsii** [comment]
Not just searching scores in decreasing order. We maintain the current highest scores in each pyramid layer and ignore the nodes whose score are below the current highest score. This could lead to a non-optimal solution but can greatly accelerate the performance.

We will release this part source code soon.

**Comment by zuowei1998** [comment]
Thank you very much for your reply. However, updating the score threshold by finding the "best score" of the leaf node through DFS can also avoid redundant calculations of other root nodes with lower scores, and at the same time increase the accuracy of the search.

**Comment by GyoungTaeChae** [comment]
@Ericsii  i've implemented like this, using koide's bbs_localization , it is right implementation? 
i hope you could check this out. thanks!

```
boost::optional<Eigen::Isometry2f> BBSLocalization::localize(const BBSLocalization::Points& scan_points, double min_score, double* best_score) {
  theta_resolution = std::acos(1 - std::pow(gridmap_pyramid[0]->grid_resolution(), 2) / (2 * std::pow(params.max_range, 2)));

  double best_score_storage;
  best_score = best_score ? best_score : &best_score_storage;

  *best_score = min_score;
  boost::optional<DiscreteTransformation> best_trans;

  auto trans_queue = create_init_transset(scan_points);

  ROS_INFO_STREAM("Branch-and-Bound");

  // Map to store the highest score at each level
  std::unordered_map<int, double> level_best_scores;

  while (!trans_queue.empty()) {
    auto trans = trans_queue.top();
    trans_queue.pop();

    // Initialize or check the highest score at the current level
    if (level_best_scores.find(trans.level) == level_best_scores.end()) {
      level_best_scores[trans.level] = trans.score;
    }

    // Pruning: Skip nodes whose score is lower than the highest score at the current level
    if (trans.score < level_best_scores[trans.level]) {
      continue;
    }

    // Update the highest score at the current level
    level_best_scores[trans.level] = std::max(level_best_scores[trans.level], trans.score);

    if (trans.is_leaf()) {
      
      if (trans.score > *best_score) {
        best_trans = trans;
        *best_score = trans.score;
      }
    } else {
      auto children = trans.branch();
      for (auto& child : children) {
        child.calc_score(scan_points, theta_resolution, gridmap_pyramid);
        trans_queue.push(child);
      }
    }
  }

  if (best_trans == boost::none) {
    return boost::none;
  }

  return best_trans->transformation(theta_resolution, gridmap_pyramid);
}

```
