### ISSUE TITLE
How do I use my own map?

### ISSUE THREAD

**Issue by njauwangkai** [YixFeng/Block-Map-Based-Localization#3]
Thank you very much for the open source, I would like to experiment with repositioning using a map I created myself. I would like to ask if I can use the slam algorithm to build smaller point cloud maps and then perform relocation tests on this map? And is it necessary to convert the map to NCLT dataset format in order to convert it to block map for localisation? I'm very sorry, I haven't touched NCLT before, all I've seen on the internet is converting NCLT to bag, I haven't seen any introduction of converting bag or data collected by my own sensors to nclt, I've been confused for months, I hope to get your reply. Thank you very much.

**Comment by YixFeng** [comment]
You have two options:
1. You need to build your block maps using [Block_Map_from_Groundtruth](https://github.com/YixFeng/Block_Map_from_Groundtruth) with ground-truth poses in NCLT gt format.
2. You can use other SLAM systems to build the maps, but the localization error will derive from both the mapping method and BM-Loc. Moreover, if you want to relocalize in block maps, you need to modify your SLAM algorithm to cut the whole map into blocks.

**Comment by njauwangkai** [comment]
Thank you very much for your prompt reply, I'll try the second method. Thanks again!
